twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - 'form_div_layout.html.twig'
        - 'form/custom_form_theme.html.twig'
when@test:
    twig:
        strict_variables: true
